name: Skeet from GitHub Actions

on:
  push:
    branches:
      - main
    paths:
      - bdn_mosquito_update_table.png
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SCRAPE_DATA_SECRET }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install datetime
          pip install atproto
          pip install requests

      - name: Debug Environment Variables
        run: |
          echo "BSKY_KEY=${{ secrets.BSKY_KEY }}"

      - name: Skeet a message
        env:
          BSKY_KEY: ${{ secrets.BSKY_KEY }}
          
        run: |
          python skeet_update_bdn.py
