on:

  push:
 # schedule:
 #  - cron: '0 * * * *' # This will run the workflow at the beginning of every hour

jobs:
  run-python-script:
    runs-on: windows-latest
    steps:
      - name: Set up environment variables
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          ACCESS_SECRET: ${{ secrets.ACCESS SECRET }}
          USER_KEY: ${{ secrets.USER KEY }}
          USER_SECRET: ${{ secrets.USER SECRET }}

      - name: Run Python script
        run: python main.py
