name: Update Figure

on:
  schedule:
    - cron: '15 * * * *' # This will run the workflow at 15-after every hour

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse 
            any::janitor
            any::sf

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        run: Rscript -e 'source("update_wpg_figure.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add wpg_mosquito_map_tmp.png
          git commit -m 'Figure updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
