name: Update Brandon Figure

on:
  push:
    branches:
      - main
    paths:
      - mosquito_data_bdn.csv

jobs:

  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse 
            any::janitor
            any::gt
            any::webshot

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SCRAPE_DATA_SECRET }}

      - name: Import data
        run: Rscript -e 'source("update_bdn_figure.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add bdn_mosquito_update_table.png
          git commit -m 'Brandon Figure updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
